# Server (worker runs on different port)
server.port=1235

# Service Name (IMPORTANT)
spring.application.name=summarizer-work-service

# PostgreSQL (same database as API)
spring.datasource.url=jdbc:postgresql://localhost:5432/asyncsummarizer
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=summarizer-worker-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.topic=summarization-jobs
kafka.group-id=summarizer-worker-group

# Google Gemini API Key
gemini.api.key= #api key here

# Logging (NEW)
logging.file.name=logs/summarizer-work-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level [%thread] %logger - ${spring.application.name} - %msg%n